name = "shan/futures"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'shan/futures'"

[repository]
user = "shan"
project = "futures"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.8.0"
source = "github"
